Add embedded files for ui
Gentleman-Programming/GoBaby pull request #1
Opened 2024-04-23 14:03 UTC by ljgago

Hola!

En Go existe la posibilidad de "embeber" los archivos estáticos (los archivos html, css, etc) dentro del mismo binario. Esto te brinda mas portabilidad y te evita estar moviendo todos los assets en una carpeta aparte.

Esto se hace utilizando la directiva `//go:embed` [doc](https://pkg.go.dev/embed).

Acá actualicé necesarios para su implementación.

Saludos!

2024-04-23 16:06 UTC, AppleLAN commented on ui/embed.go
> +//go:embed html/* static/*
Me gusta ! veo que existe apartir de la version 1.16, perfecto !

2024-04-23 16:10 UTC, AppleLAN requested changes
Me gusta !!!! dime qué piensas de mis comentarios :) GRACIAS !

2024-04-23 16:10 UTC, AppleLAN commented on internal/utils/template.go
> +	ts, er := template.ParseFS(ui.Content, files...)
estaría genial que ui.Content venga como parámetro a ParseTemplateFiles por si el contenido proviene de otro paquete

2024-04-23 16:10 UTC, AppleLAN commented on cmd/web/routes/starter.route.go
> +	static, _  = fs.Sub(ui.Content, "static")
Me gusta ! se podría también separar en un método como la inicialización de rutas para dejarlo dividido o poner un comment

2024-04-23 16:54 UTC, ljgago commented on internal/utils/template.go
> +	ts, er := template.ParseFS(ui.Content, files...)
Dale! no hay problema.

2024-04-23 16:57 UTC, ljgago commented on cmd/web/routes/starter.route.go
> +	static, _  = fs.Sub(ui.Content, "static")
La linea 12 no me gustaba mucho porque queda esa variable colgada.

2024-04-23 18:51 UTC, ljgago commented
Ahí subí algunos cambios.

2024-04-24 14:57 UTC, AppleLAN approved these changes

2024-04-24 14:57 UTC, merged